#! /usr/bin/env php
<?php

if(phpversion() < '5.6')
{
    die('PHP 5.6 is REQUIRED. Please update your php installation.');
}

/**
 * Dan loader file.
 * Do not directly edit this file.
 */
define("ROOT_DIR", __DIR__);

$dan = require(__DIR__ . '/bootloader.php');

//Boot the bot
$dan->boot($argv);
